In [1]:
#numpy is an open-source library that is used for handle scientific calculations 
#why numpy is better than list
#1 Numpy > homogenous data type ,list > hetrogenuos 
#2 memory and time consumption > less in numpy high in list

In [2]:
!pip install numpy


   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ----------- ---------------------------- 3.7/12.6 MB 24.3 MB/s eta 0:00:01
   --------------------------- ------------ 8.7/12.6 MB 24.5 MB/s eta 0:00:01
   ---------------------------------------  12.6/12.6 MB 22.5 MB/s eta 0:00:01
   ---------------------------------------- 12.6/12.6 MB 20.9 MB/s eta 0:00:00


In [3]:
import numpy as np

In [4]:
a=[1,2,4]
b=np.array(a)#converting list into numpy array 
b

array([1, 2, 4])

In [7]:
print(type(b))
print(type(a))

<class 'numpy.ndarray'>
<class 'list'>


In [10]:
print("shape",b.shape)#shape=n(rows),n(colimns)
print("dimension",b.ndim)# number of dimension
print("total elemnets",b.size)#total elemnts n(rows)*n(col)

shape (3,)
dimension 1
total elemnets 3


In [17]:
a=[[12,3,3],[1,2,3],[2,1,2]]
b=np.array(a)
b

array([[12,  3,  3],
       [ 1,  2,  3],
       [ 2,  1,  2]])

In [18]:
print(b.shape)#total row column
print(b.ndim)
print(b.size)

(3, 3)
2
9


In [19]:
#user defined array

In [28]:
a=[]
b=int(input("how many elemnets want"))
for i in range(b):
    val=int(input("enter va;lues"))
    a.append(val)
b=np.array(a)
b

how many elemnets want 3
enter va;lues 1
enter va;lues 2
enter va;lues 3


array([1, 2, 3])

In [29]:
#pre defined functions 


In [30]:
#1 zeros()> this is pre defined function of numpy that will return all the values zero 
#either one or multi dimensional array

In [33]:
a=np.zeros(4)
print(a)
type(a)

[0. 0. 0. 0.]


numpy.ndarray

In [35]:
a=np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [36]:
#2 ones()> this is also pre defined function of numpy and it will return all the value one 

In [38]:
a=np.ones(3)
a

array([1., 1., 1.])

In [41]:
a=np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [42]:
a=np.ones(3)
a

array([1., 1., 1.])

In [43]:
#images > pixels (0,255)> black and white images=height,width
#colorful images =height ,width,color_channel(red,green,blue)
#machine learning > actual answer ,prediction answer > optimization technique(m,b)


In [44]:
#3 eye()>it will create an array in which diagonal posiotons elements are 1 rest all are 0

In [47]:
a=np.eye(3,8)#assymetric matrix 
a

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.]])

In [50]:
a=np.eye(4,4)#symmatric matrix n(row)=n(col)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [49]:
a=[]
size=int(input("enter size of array"))
for i in range(size):
    val=int(input("enter values"))
    a.append(val)
b=np.array(a)
b

enter size of array 3
enter values 1
enter values 2
enter values 3


array([1, 2, 3])