In [1]:
#numpy is an open-source library that is used for handle scientific calculations 
#why numpy is better than list
#1 Numpy > homogenous data type ,list > hetrogenuos 
#2 memory and time consumption > less in numpy high in list

In [2]:
!pip install numpy


   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ----------- ---------------------------- 3.7/12.6 MB 24.3 MB/s eta 0:00:01
   --------------------------- ------------ 8.7/12.6 MB 24.5 MB/s eta 0:00:01
   ---------------------------------------  12.6/12.6 MB 22.5 MB/s eta 0:00:01
   ---------------------------------------- 12.6/12.6 MB 20.9 MB/s eta 0:00:00


In [3]:
import numpy as np

In [4]:
a=[1,2,4]
b=np.array(a)#converting list into numpy array 
b

array([1, 2, 4])

In [7]:
print(type(b))
print(type(a))

<class 'numpy.ndarray'>
<class 'list'>


In [10]:
print("shape",b.shape)#shape=n(rows),n(colimns)
print("dimension",b.ndim)# number of dimension
print("total elemnets",b.size)#total elemnts n(rows)*n(col)

shape (3,)
dimension 1
total elemnets 3


In [17]:
a=[[12,3,3],[1,2,3],[2,1,2]]
b=np.array(a)
b

array([[12,  3,  3],
       [ 1,  2,  3],
       [ 2,  1,  2]])

In [18]:
print(b.shape)#total row column
print(b.ndim)
print(b.size)

(3, 3)
2
9


In [19]:
#user defined array

In [28]:
a=[]
b=int(input("how many elemnets want"))
for i in range(b):
    val=int(input("enter va;lues"))
    a.append(val)
b=np.array(a)
b

how many elemnets want 3
enter va;lues 1
enter va;lues 2
enter va;lues 3


array([1, 2, 3])

In [29]:
#pre defined functions 


In [30]:
#1 zeros()> this is pre defined function of numpy that will return all the values zero 
#either one or multi dimensional array

In [33]:
a=np.zeros(4)
print(a)
type(a)

[0. 0. 0. 0.]


numpy.ndarray

In [35]:
a=np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [36]:
#2 ones()> this is also pre defined function of numpy and it will return all the value one 

In [38]:
a=np.ones(3)
a

array([1., 1., 1.])

In [41]:
a=np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [42]:
a=np.ones(3)
a

array([1., 1., 1.])

In [43]:
#images > pixels (0,255)> black and white images=height,width
#colorful images =height ,width,color_channel(red,green,blue)
#machine learning > actual answer ,prediction answer > optimization technique(m,b)


In [44]:
#3 eye()>it will create an array in which diagonal posiotons elements are 1 rest all are 0

In [47]:
a=np.eye(3,8)#assymetric matrix 
a

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.]])

In [50]:
a=np.eye(4,4)#symmatric matrix n(row)=n(col)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [49]:
a=[]
size=int(input("enter size of array"))
for i in range(size):
    val=int(input("enter values"))
    a.append(val)
b=np.array(a)
b

enter size of array 3
enter values 1
enter values 2
enter values 3


array([1, 2, 3])

In [15]:
class student:
     def __init__(self,name,age):
         self.name=name
         self.age=age
         subscore=[]#making list 
         hh={} #making dictionary 
     def subject(self,subscore):
         return subscore

     def dic(self,hh):
         return hh
s1=student("chirag",19)
s1.name
s1.age
print(s1.subject([100,2,3]))
print(s1.dic({"chirag":100}))




         

[100, 2, 3]
{'chirag': 100}


In [1]:
#diag()>it will create an array which we set diagonal array

In [4]:
import   numpy as np

In [5]:
a=np.array([12,23,44,55])
a

array([12, 23, 44, 55])

In [8]:
b=np.diag(a)
b

array([[12,  0,  0,  0],
       [ 0, 23,  0,  0],
       [ 0,  0, 44,  0],
       [ 0,  0,  0, 55]])

In [9]:
#random module 

In [10]:
#1. randint()>randint(minrange,maxrange,totalnumber)

In [13]:
a=np.random.randint(1,95,4)
a

array([35, 88, 56, 10], dtype=int32)

In [14]:
#rand()>it will generate random number in range 0 to 1

In [15]:
a=np.random.rand(4)
a

array([0.86255834, 0.2520972 , 0.53748246, 0.58975771])

In [20]:
a=np.random.rand(2,3)
a

array([[0.42053804, 0.859182  , 0.17116155],
       [0.33886396, 0.27053283, 0.69104135]])

In [17]:
#seed()> it will fix our random values 

In [19]:
np.random.seed(22)#in argument pass number anything it doesnt affect anything but passes the nunber 
a=np.random.randint(1,6,3)
a

array([5, 5, 1], dtype=int32)

In [21]:
#view> modification in origina;l data 
#copy > modification in copy data doesnt affect original data

In [22]:
a=np.array([10,20,30,40,50])
a

array([10, 20, 30, 40, 50])

In [25]:
#view
b= a[2:4]
b[:]=1
print(b)
print(a)

[1 1]
[10 20  1  1 50]


In [27]:
a=np.array([10,20,3,4,5,6,77])
a

array([10, 20,  3,  4,  5,  6, 77])

In [29]:
#copy 
b=a[3:5].copy()
b[:]=0
print(b)
print(a)

[0 0]
[10 20  3  4  5  6 77]


In [30]:
# conditional selection in numpy 


In [32]:
a=np.arange(1,10,1)#like for loop to print numbers in given range and givemn gap 
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
b=a>2
b

array([False, False,  True,  True,  True,  True,  True,  True,  True])

In [35]:
b=a>2
a[b]

array([3, 4, 5, 6, 7, 8, 9])

In [37]:
#even number in array
b=a%2==0
a[b]

array([2, 4, 6, 8])

In [38]:
#reshaping the array

In [40]:
a=np.array([1,2,3,4]).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [43]:
b=np.array([1,2,3,1]).reshape(2,2)
b

array([[1, 2],
       [3, 1]])

In [44]:
a+b#matrix a plus b matrix 

array([[2, 4],
       [6, 5]])

In [45]:
b-a#substrsact matrixes 

array([[ 0,  0],
       [ 0, -3]])

In [46]:
a.dot(b)#for multiplying matrixes


array([[ 7,  4],
       [15, 10]])

In [47]:
a=np.random.randint(1,50,12)
a

array([46, 25, 30, 40, 35, 42,  9, 41,  6, 48, 28, 21], dtype=int32)

In [48]:
a.reshape(4,3)

array([[46, 25, 30],
       [40, 35, 42],
       [ 9, 41,  6],
       [48, 28, 21]], dtype=int32)

In [50]:
a.reshape(2,6)

array([[46, 25, 30, 40, 35, 42],
       [ 9, 41,  6, 48, 28, 21]], dtype=int32)

In [52]:
a=np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
np.sum(a)#sum of array elements 

np.int64(45)

In [54]:
np.sum(a,axis=0)#axis =0 column wise sum

array([12, 15, 18])

In [55]:
np.sum(a,axis=1)#row wise sum

array([ 6, 15, 24])

In [56]:
#unique()---> it will create an array in which we have unique values
# return 3 array
# arr --- > unique array 
# return_index=True --> unique values inderxing
#return_counts=True --> unique values frequency 


In [57]:
a=np.array([1,2,3,4,1,1,2,2,3])
a

array([1, 2, 3, 4, 1, 1, 2, 2, 3])

In [59]:
np.unique(a, return_index=True ,return_counts=True)#it shows array then index values and then frequency of elements 


(array([1, 2, 3, 4]), array([0, 1, 2, 3]), array([3, 3, 2, 1]))

In [60]:
#linspace()--> oit will return same gap values 


In [62]:
a=np.linspace(1,5,3)#gap is 2 it is samew in all elements 
a

array([1., 3., 5.])

In [63]:
#stacking 
#1 hstack()


In [65]:
a=np.array([1,2,3])
b=np.array([4,5,6])
np.hstack((a,b))#it merges arrays in horizontal

array([1, 2, 3, 4, 5, 6])

In [66]:
#vstack 
a=np.array([1,2,33])
b=np.array([2,5,6])
np.vstack((a,b))#it merges array in vertical

array([[ 1,  2, 33],
       [ 2,  5,  6]])